In [ ]:
!pip install pandas numpy torch scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.5)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [ ]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [ ]:
!kaggle datasets download -d ayenuryrr/loghub-hdfs-hadoop-distributed-file-system-data
!unzip loghub-hdfs-hadoop-distributed-file-system-data.zip

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kaggle/cli.py", line 68, in main
    out = args.func(**command_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kaggle/api/kaggle_api_extended.py", line 1741, in dataset_download_cli
    with self.build_kaggle_client() as kaggle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kaggle/api/kaggle_api_extended.py", line 688, in build_kaggle_client
    username=self.config_values['username'],
             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'username'
unzip:  cannot find or open loghub-hdfs-hadoop-distributed-file-system-data.zip, loghub-hdfs-hadoop-distributed-file-system-data.zip.zip or loghub-hdfs-hadoop-distributed-file-system-data.zip.ZIP.

In [ ]:
import kagglehub
import os
import pandas as pd

path = kagglehub.dataset_download(
    "ayenuryrr/loghub-hdfs-hadoop-distributed-file-system-data"
)

print("Dataset path:", path)

print(os.listdir(path))

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/ayenuryrr/loghub-hdfs-hadoop-distributed-file-system-data?dataset_version_number=3...

100%|██████████| 1.55G/1.55G [00:16<00:00, 103MB/s]

Extracting files...

Dataset path: /root/.cache/kagglehub/datasets/ayenuryrr/loghub-hdfs-hadoop-distributed-file-system-data/versions/3
['HDFS_v2', 'HDFS_2k', 'HDFS_v3_TraceBench', 'HDFS_v1']

In [ ]:
import os

base_path = "/root/.cache/kagglehub/datasets/ayenuryrr/loghub-hdfs-hadoop-distributed-file-system-data/versions/3/HDFS_2k"

os.listdir(base_path)

['HDFS_2k.log', 'HDFS_2k.log_templates.csv', 'HDFS_2k.log_structured.csv']

In [ ]:
import pandas as pd
import os

base_path = "/root/.cache/kagglehub/datasets/ayenuryrr/loghub-hdfs-hadoop-distributed-file-system-data/versions/3/HDFS_2k"

df = pd.read_csv(os.path.join(base_path, "HDFS_2k.log_structured.csv"))

df.head()

,LineId,Date,Time,Pid,Level,Component,Content,EventId,EventTemplate
0,1,81109,203615,148,INFO,dfs.DataNode$PacketResponder,PacketResponder 1 for block blk_38865049064139...,E10,PacketResponder <*> for block blk_<*> terminating
1,2,81109,203807,222,INFO,dfs.DataNode$PacketResponder,PacketResponder 0 for block blk_-6952295868487...,E10,PacketResponder <*> for block blk_<*> terminating
2,3,81109,204005,35,INFO,dfs.FSNamesystem,BLOCK* NameSystem.addStoredBlock: blockMap upd...,E6,BLOCK* NameSystem.addStoredBlock: blockMap upd...
3,4,81109,204015,308,INFO,dfs.DataNode$PacketResponder,PacketResponder 2 for block blk_82291938032499...,E10,PacketResponder <*> for block blk_<*> terminating
4,5,81109,204106,329,INFO,dfs.DataNode$PacketResponder,PacketResponder 2 for block blk_-6670958622368...,E10,PacketResponder <*> for block blk_<*> terminating

In [ ]:
import re

df["BlockId"] = df["Content"].str.extract(r'(blk_-?\d+)')

sequences = df.groupby("BlockId")["EventId"].apply(list)

sequences.head()

BlockId
blk_-1030832046197982436     [E8]
blk_-1046472716157313227     [E9]
blk_-1049340855430710153    [E10]
blk_-1055254430948037872     [E6]
blk_-1067234447809438340    [E10]
Name: EventId, dtype: object

In [ ]:
!git clone https://github.com/wuyifan18/DeepLog.git

Cloning into 'DeepLog'...
remote: Enumerating objects: 189, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 189 (delta 49), reused 48 (delta 47), pack-reused 132 (from 1)
Receiving objects: 100% (189/189), 1.49 MiB | 3.85 MiB/s, done.
Resolving deltas: 100% (97/97), done.

In [ ]:
%cd DeepLog

/content/DeepLog

In [ ]:
!pip install torch pandas numpy scikit-learn

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [ ]:
!cp /root/.cache/kagglehub/datasets/ayenuryrr/loghub-hdfs-hadoop-distributed-file-system-data/versions/3/HDFS_2k/HDFS_2k.log_structured.csv .

In [ ]:
import pandas as pd
import re

df = pd.read_csv("HDFS_2k.log_structured.csv")

df["BlockId"] = df["Content"].str.extract(r'(blk_-?\d+)')

sequences = df.groupby("BlockId")["EventId"].apply(list)

print(sequences.head())

BlockId
blk_-1030832046197982436     [E8]
blk_-1046472716157313227     [E9]
blk_-1049340855430710153    [E10]
blk_-1055254430948037872     [E6]
blk_-1067234447809438340    [E10]
Name: EventId, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

all_events = [e for seq in sequences for e in seq]
encoder.fit(all_events)

sequences = [[encoder.transform([e])[0] for e in seq] for seq in sequences]

In [ ]:
!ls -R

.:
data			    LICENSE		    README.md
dataView.py		    LogKeyModel_predict.py  requirements.txt
HDFS_2k.log_structured.csv  LogKeyModel_train.py    visual.py

./data:
hdfs_test_abnormal  hdfs_test_normal  hdfs_train

In [ ]:
!python LogKeyModel_train.py

2026-03-15 14:59:00.347471: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-15 14:59:00.353801: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-15 14:59:00.369308: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1773586740.398137    4808 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1773586740.405361    4808 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1773586740.425905    4808 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1773586740.425964    4808 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1773586740.425968    4808 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1773586740.425973    4808 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-15 14:59:00.431817: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Number of sessions(hdfs_train): 4855
Number of seqs(hdfs_train): 46575
/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch [1/30], train_loss: 2.8381
Epoch [2/30], train_loss: 1.8844
Epoch [3/30], train_loss: 1.6926
Epoch [4/30], train_loss: 1.4178
Epoch [5/30], train_loss: 1.1519
Epoch [6/30], train_loss: 0.9554
Epoch [7/30], train_loss: 0.8297
Epoch [8/30], train_loss: 0.7438
Epoch [9/30], train_loss: 0.6832
Epoch [10/30], train_loss: 0.6350
Epoch [11/30], train_loss: 0.5974
Epoch [12/30], train_loss: 0.5632
Epoch [13/30], train_loss: 0.5327
Epoch [14/30], train_loss: 0.5079
Epoch [15/30], train_loss: 0.4831
Epoch [16/30], train_loss: 0.4635
Epoch [17/30], train_loss: 0.4506
Epoch [18/30], train_loss: 0.4343
Epoch [19/30], train_loss: 0.4271
Epoch [20/30], train_loss: 0.4154
Epoch [21/30], train_loss: 0.4075
Epoch [22/30], train_loss: 0.4003
Epoch [23/30], train_loss: 0.3936
Epoch [24/30], train_loss: 0.3935
Epoch [25/30], train_loss: 0.3865
Epoch [26/30], train_loss: 0.3807
Epoch [27/30], train_loss: 0.3746
Epoch [28/30], train_loss: 0.3758
Epoch [29/30], train_loss: 0.3698
Epoch [30/30], train_loss: 0.3683
elapsed_time: 804.288s
Finished Training

In [ ]:
!ls model

'Adam_batch_size=2048_epoch=30.pt'

In [ ]:
!python LogKeyModel_predict.py

model_path: model/Adam_batch_size=2048_epoch=30.pt
Number of sessions(hdfs_test_normal): 14177
Number of sessions(hdfs_test_abnormal): 4123
elapsed_time: 201.936s
false positive (FP): 1179, false negative (FN): 225, Precision: 76.778%, Recall: 94.543%, F1-measure: 84.739%
Finished Predicting

In [ ]:
normal_sessions = 14177
abnormal_sessions = 4123
FP = 1179
FN = 225

TN = normal_sessions - FP
TP = abnormal_sessions - FN

accuracy = (TP + TN) / (normal_sessions + abnormal_sessions)

print("Accuracy:", accuracy)
print("Accuracy (%):", accuracy * 100)

Accuracy: 0.9232786885245902
Accuracy (%): 92.32786885245902